// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID                   pgtype.UUID        `json:"id"`
	AccessToken          pgtype.Text        `json:"access_token"`
	RefreshToken         pgtype.Text        `json:"refresh_token"`
	SessionData          pgtype.Text        `json:"session_data"`
	UserAgent            string             `json:"user_agent"`
	ClientIp             string             `json:"client_ip"`
	IsBlocked            pgtype.Bool        `json:"is_blocked"`
	LastActive           pgtype.Timestamptz `json:"last_active"`
	ExpiresAt            time.Time          `json:"expires_at"`
	SessionLengthSeconds pgtype.Int4        `json:"session_length_seconds"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}
