// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BlockSession(ctx context.Context, arg BlockSessionParams) (Session, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	UpdateSessionData(ctx context.Context, arg UpdateSessionDataParams) (Session, error)
}

var _ Querier = (*Queries)(nil)
